# .github/workflows/auto-enable-automerge.yml
name: Auto-enable auto-merge on PRs to main

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_automerge:
    # skip drafts and PRs from forks
    if: >
      github.event.pull_request.draft == false &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GH CLI (uses GITHUB_TOKEN)
        run: gh auth status || gh auth login --with-token <<< "${GITHUB_TOKEN}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Enable auto-merge (change method if you prefer)
        run: gh pr merge "${{ github.event.pull_request.number }}" --auto --squash
        env:
          GITHUB_TOKEN: ${{ github.token }}
