name: Auto-enable auto-merge on PRs to main

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable_automerge:
    # skip drafts and PRs from forks
    if: >
      github.event.pull_request.draft == false &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: cli/cli-action@v2
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR="${{ github.event.pull_request.number }}"
          # Choose one: --merge | --squash | --rebase
          gh pr merge "$PR" --auto --squash
