name: Enable auto-merge on PR open
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    # Only do this for PRs targeting main. Change 'main' if your default branch is different.
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/cli-action@v2
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR="${{ github.event.pull_request.number }}"
          # Choose ONE strategy: --merge | --squash | --rebase
          gh pr merge "$PR" --auto --squash
